name: apppdf
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  file_picker: ^5.2.11
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  path_provider: ^2.0.14
  syncfusion_flutter_pdf: ^21.1.41
  syncfusion_flutter_pdfviewer: ^21.1.41

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

assets: -assets/documents/prueba.pdf
